# Generated by Django 5.1.6 on 2025-02-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_user_facebook_link_user_first_carousel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='structure_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
