# Generated by Django 5.1.6 on 2025-02-26 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_comments_user_structure_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='code_center',
            new_name='entreprise',
        ),
        migrations.AddField(
            model_name='product',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.codecenter'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.codecenter'),
        ),
    ]
