# Generated by Django 5.1.6 on 2025-02-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_rename_code_center_user_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codecenter',
            options={},
        ),
    ]
