# Generated by Django 5.1.6 on 2025-02-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_codecenter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codecenter',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='codecenter',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
